kind: pipeline
type: kubernetes
name: test

trigger:
  event:
  - push
  - pull_request

steps:
- name: test
  image: golang
  commands:
  - go test
  - go vet
  - go build
---
kind: pipeline
type: kubernetes
name: build and publish

trigger:
  branches:
  - main
  event:
  - tag

steps:
- name: build
  image: golang
  commands:
  - bash scripts/compile.sh
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files:
    - build/*
    title: Release $DRONE_TAG